FROM python:3.10-slim

WORKDIR /app

# Copy unified requirements from root context
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy specific pipeline files into workspace
COPY pipeline/pipeline.py .

# Run training loop execution upon service start
CMD ["python", "pipeline.py"]
